// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkd5DaWaGm_FMiRbrE5fX5z2tPmHHtdDk',
    appId: '1:27211140087:web:bed52c8b3938ed6149bcf2',
    messagingSenderId: '27211140087',
    projectId: 'hyper-garage-sale-a3238',
    authDomain: 'hyper-garage-sale-a3238.firebaseapp.com',
    storageBucket: 'hyper-garage-sale-a3238.appspot.com',
    measurementId: 'G-9KPF79P8KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnmWU41rDw94Uw3pAiByC3KLpKCUy9Swg',
    appId: '1:27211140087:android:21c885e0f825d69949bcf2',
    messagingSenderId: '27211140087',
    projectId: 'hyper-garage-sale-a3238',
    storageBucket: 'hyper-garage-sale-a3238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc5HRy14iazpBuWt8hftSlqhg_f05j_DU',
    appId: '1:27211140087:ios:5db4f66ad1b6a79049bcf2',
    messagingSenderId: '27211140087',
    projectId: 'hyper-garage-sale-a3238',
    storageBucket: 'hyper-garage-sale-a3238.appspot.com',
    androidClientId: '27211140087-to9riffrffeugjos5qfdchgfpm9v21sl.apps.googleusercontent.com',
    iosClientId: '27211140087-fp5govv3k2bp5rlvdha45nte4lr2j3k1.apps.googleusercontent.com',
    iosBundleId: 'com.raj.hyperGarageSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc5HRy14iazpBuWt8hftSlqhg_f05j_DU',
    appId: '1:27211140087:ios:b0d63edcd688094049bcf2',
    messagingSenderId: '27211140087',
    projectId: 'hyper-garage-sale-a3238',
    storageBucket: 'hyper-garage-sale-a3238.appspot.com',
    androidClientId: '27211140087-to9riffrffeugjos5qfdchgfpm9v21sl.apps.googleusercontent.com',
    iosClientId: '27211140087-4ojqsrk3nivfu4d8oevjqnuldl586gat.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );
}
